version: 2
jobs:
  build:
    docker:
      - image: circleci/node 
    working_directory: ~/zokrates-js
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Generate cargo lockfile
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run: 
          name: Run build
          command: ./scripts/build_docker.sh
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
